# Generated by Django 4.1.5 on 2023-11-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0007_managementprofil_city_managementprofil_sex'),
        ('school_management', '0014_alter_schedule_end_hours_alter_schedule_start_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('payment_month', models.CharField(max_length=20)),
                ('day_of_payment', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('date_payment', models.DateField()),
                ('amount_payment', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default_amount', models.IntegerField(default=0)),
                ('defaut_quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_to_tranche', models.BooleanField(default=True)),
                ('analytic_code', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timline_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_invoice_and_accounting.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('payment_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.career')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_invoice_and_accounting.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_invoice_and_accounting.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fees', models.IntegerField()),
                ('send_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50, unique=True)),
                ('date_estimate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.career')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_invoice_and_accounting.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_invoice_and_accounting.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_number', models.CharField(max_length=100)),
                ('donate_date', models.DateField()),
                ('donate_amount', models.FloatField()),
                ('reason_for_donation', models.TextField()),
                ('donate_type', models.CharField(max_length=20)),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_firstname', models.CharField(max_length=50)),
                ('donor_address', models.CharField(max_length=50)),
                ('donor_postal_code', models.CharField(max_length=8)),
                ('donor_city', models.CharField(max_length=50)),
                ('donor_country', models.CharField(max_length=50)),
                ('donor_tel', models.CharField(max_length=20)),
                ('donor_email', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donate_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.academicyear')),
            ],
        ),
    ]
