# Generated by Django 5.0 on 2023-12-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_invoice_and_accounting', '0001_initial'),
        ('user_account', '0008_managementprofil_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('date_payment', models.DateField()),
                ('amount_payment', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BillingBracket',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='career',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='item',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='student',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='item',
            name='timline_model',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='item',
            name='submitted_to_tranche',
        ),
        migrations.AddField(
            model_name='regulations',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_invoice_and_accounting.invoice'),
        ),
        migrations.AddField(
            model_name='regulations',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student'),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
    ]
