# Generated by Django 5.0 on 2023-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_invoice_and_accounting', '0002_regulations_delete_billingbracket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcommitment',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialcommitment',
            name='send_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
