# Generated by Django 5.0 on 2023-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_invoice_and_accounting', '0003_financialcommitment_is_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now=True),
        ),
    ]
