# Generated by Django 5.0 on 2023-12-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_invoice_and_accounting', '0004_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcommitment',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
