# Generated by Django 5.0 on 2023-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_invoice_and_accounting', '0005_alter_financialcommitment_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='date_payment',
            field=models.DateField(auto_now=True),
        ),
    ]
