# Generated by Django 4.1.5 on 2024-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_invoice_and_accounting', '0008_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Espèce', 'Espèce'), ('Chèque', 'Chèque')], max_length=20),
        ),
    ]
