# Generated by Django 4.1.5 on 2023-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ademicyear',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
