# Generated by Django 4.1.5 on 2024-01-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_alter_subject_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcareer',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
