# Generated by Django 4.1.5 on 2023-11-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_managementprofil_city_managementprofil_sex'),
        ('school_management', '0005_groupsubject_sanctionassessmenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('obligatoire', 'Obligatoire'), ('secondaire', 'Secondaire')], max_length=12)),
                ('possible_evaluation', models.BooleanField(default=True)),
                ('possible_averaging', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.level')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.sector')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.groupsubject')),
                ('teacher_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account.teacher')),
            ],
        ),
    ]
