# Generated by Django 4.1.5 on 2023-11-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_managementprofil_city_managementprofil_sex'),
        ('school_management', '0007_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.level')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.ademicyear')),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_management.career')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
            ],
        ),
    ]
