# Generated by Django 4.1.5 on 2023-11-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_semester_studentcareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hours', models.CharField(choices=[('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h')], max_length=15)),
                ('end_hours', models.CharField(choices=[('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h'), ('06h-07h', '06h-07h')], max_length=15)),
                ('day', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.career')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.subject')),
            ],
        ),
    ]
