# Generated by Django 4.1.5 on 2023-11-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0010_rename_sanctionassessmenttype_sanctionappreciationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='career',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentcareer',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentcareer',
            name='career',
        ),
        migrations.RemoveField(
            model_name='studentcareer',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentcareer',
            name='student',
        ),
        migrations.DeleteModel(
            name='SanctionAppreciation',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='StudentCareer',
        ),
    ]
