# Generated by Django 4.1.5 on 2024-02-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablishment',
            name='currency',
            field=models.CharField(blank=True, choices=[('F CFA', 'F CFA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etablishment',
            name='status_fees',
            field=models.CharField(blank=True, choices=[('Activé', 'Activé'), ('Desactivé', 'Desactivé')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etablishment',
            name='système',
            field=models.CharField(blank=True, choices=[('Congolais', 'Congolais')], max_length=50, null=True),
        ),
    ]
