# Generated by Django 4.1.5 on 2024-02-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementprofil',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
