# Generated by Django 4.1.5 on 2024-02-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_etablishment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablishment',
            name='re_registration_fees',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='etablishment',
            name='subscription_fees',
            field=models.IntegerField(default=1000),
        ),
    ]
