# Generated by Django 4.1.5 on 2024-02-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_managementprofil_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('social_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('bulletin_foot', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('F CFA', 'F Cfa')], max_length=50)),
                ('système', models.CharField(choices=[('Congolais', 'Congolais')], max_length=50)),
                ('status_fees', models.CharField(choices=[('Activé', 'Activé'), ('Desactivé', 'Desactivé')], max_length=50)),
                ('subscription_fees', models.FloatField(default=1000)),
                ('re_registration_fees', models.FloatField(default=800)),
            ],
        ),
    ]
