# Generated by Django 4.1.5 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_etablishment_re_registration_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablishment',
            name='month',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
    ]
