# Generated by Django 4.1.5 on 2024-02-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_etablishment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_school',
            field=models.BooleanField(default=False),
        ),
    ]
