# Generated by Django 4.1.5 on 2024-02-22 09:12

import backend.models.gestion_ecole
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_is_admin_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=backend.models.gestion_ecole.ShortUUID4Field(editable=False, max_length=15, unique=True),
        ),
    ]
