# Generated by Django 4.1.5 on 2024-02-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionappreciation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
    ]
