# Generated by Django 4.1.5 on 2024-02-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_sanctionappreciation_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
    ]
