# Generated by Django 4.1.5 on 2024-02-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_studentcareer_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
