# Generated by Django 4.1.5 on 2024-02-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_invoice_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_status',
            new_name='invoice_status',
        ),
    ]
