# Generated by Django 4.1.5 on 2024-02-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_payment_status_invoice_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Regulations',
        ),
    ]
