# Generated by Django 4.1.5 on 2024-02-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_invoice_amount_delete_regulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_method', models.CharField(choices=[('Par chèque', 'Par chèque'), ('En espèce', 'En espèce')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('repayment_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.invoice')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.student')),
            ],
        ),
    ]
