# Generated by Django 4.1.5 on 2024-02-14 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
