# Generated by Django 4.1.5 on 2024-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_repayment_created_at_repayment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_repayment',
            field=models.BooleanField(default=False),
        ),
    ]
