# Generated by Django 4.1.5 on 2024-02-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='fees',
            field=models.IntegerField(default=1000),
        ),
    ]
