# Generated by Django 4.1.5 on 2024-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_level_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablishment',
            name='month',
            field=models.IntegerField(default=9),
        ),
    ]
