# Generated by Django 4.1.5 on 2024-02-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_financialcommitment_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='student',
        ),
    ]
