# Generated by Django 4.1.5 on 2024-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_teacher_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='note',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='school',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='average',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='file',
            field=models.FileField(upload_to='releves_notes'),
        ),
    ]
