# Generated by Django 4.1.5 on 2024-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_reportcard_note_remove_reportcard_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcareer',
            name='is_next',
            field=models.BooleanField(default=False),
        ),
    ]
