# Generated by Django 4.1.5 on 2024-02-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_studentcareer_is_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
        migrations.AddField(
            model_name='teacherdocument',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.etablishment'),
        ),
    ]
