# Generated by Django 4.1.5 on 2024-02-21 16:58

import backend.models.gestion_ecole
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_documenttype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=backend.models.gestion_ecole.ShortUUID4Field(editable=False, max_length=20, unique=True),
        ),
    ]
