# Generated by Django 4.1.5 on 2024-01-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_communication', '0001_initial'),
        ('school_management', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscussionmedia',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_media', to='user_account.student'),
        ),
        migrations.AddField(
            model_name='studentdiscussionmedia',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_media', to='user_account.student'),
        ),
        migrations.AddField(
            model_name='studentdiscussion',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_discussions', to='user_account.student'),
        ),
        migrations.AddField(
            model_name='studentdiscussion',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_discussions', to='user_account.student'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='discussion_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_communication.discussiongroup'),
        ),
        migrations.AddField(
            model_name='groupmedia',
            name='discussion_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_communication.discussiongroup'),
        ),
        migrations.AddField(
            model_name='group',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.career'),
        ),
        migrations.AddField(
            model_name='eventparticipate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_communication.event'),
        ),
        migrations.AddField(
            model_name='eventparticipate',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account.student'),
        ),
        migrations.AddField(
            model_name='discussiongroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_communication.group'),
        ),
        migrations.AddField(
            model_name='discussiongroup',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_account.student'),
        ),
        migrations.AddField(
            model_name='contact',
            name='can_discuss_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='can_be_discussed_with', to='user_account.student'),
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='user_account.student'),
        ),
    ]
