# Generated by Django 4.1.5 on 2023-11-09 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0013_rename_ademicyear_academicyear_and_more'),
        ('module_communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussiongroup',
            name='career',
        ),
        migrations.AddField(
            model_name='group',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management.career'),
        ),
    ]
