# Generated by Django 4.1.5 on 2023-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_communication', '0002_remove_discussiongroup_career_group_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipate',
            name='end_hours',
            field=models.CharField(choices=[('06h-07h', '06h-07h'), ('07h-08h', '07h-08h'), ('08h-09h', '08h-09h'), ('09h-10h', '09h-10h'), ('10h-11h', '10h-11h'), ('11h-12h', '11h-12h'), ('12h-13h', '12h-13h'), ('13h-14h', '13h-14h'), ('14h-15h', '14h-15h'), ('15h-16h', '15h-16h'), ('16h-17h', '16h-17h')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventparticipate',
            name='start_hours',
            field=models.CharField(choices=[('06h-07h', '06h-07h'), ('07h-08h', '07h-08h'), ('08h-09h', '08h-09h'), ('09h-10h', '09h-10h'), ('10h-11h', '10h-11h'), ('11h-12h', '11h-12h'), ('12h-13h', '12h-13h'), ('13h-14h', '13h-14h'), ('14h-15h', '14h-15h'), ('15h-16h', '15h-16h'), ('16h-17h', '16h-17h')], max_length=20),
        ),
    ]
