# Generated by Django 4.1.5 on 2024-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_communication', '0005_alter_information_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
