# Generated by Django 4.1.5 on 2024-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_communication', '0007_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date_info',
            field=models.DateField(blank=True, null=True),
        ),
    ]
