# Generated by Django 4.1.5 on 2024-01-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementprofil',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='managements_images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images'),
        ),
    ]
