# Generated by Django 4.1.5 on 2023-11-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_managementprofil_teacher_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementProfil',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
