# Generated by Django 4.1.5 on 2023-11-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_managementprofil_address_managementprofil_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementprofil',
            name='city',
            field=models.CharField(blank=True, choices=[('pointe_noire', 'Pointe Noire'), ('brazzaville', 'Brazzaville')], max_length=17),
        ),
        migrations.AddField(
            model_name='managementprofil',
            name='sex',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10),
        ),
    ]
