# Generated by Django 5.0 on 2023-12-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_user_is_student_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='management_profil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_account.managementprofil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_account.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_account.teacher'),
        ),
    ]
