# Generated by Django 5.0 on 2023-12-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_alter_user_management_profil_alter_user_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='management_profil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.managementprofil'),
        ),
    ]
