# Generated by Django 4.1.5 on 2024-01-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_alter_user_management_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='last_diploma',
            field=models.CharField(blank=True, choices=[('Doctorat', 'Doctorat'), ('Master', 'Master'), ('Licence', 'Licence'), ('DUT', 'DUT'), ('Baccalauréat', 'Baccalauréat')], max_length=20),
        ),
    ]
