# Generated by Django 4.1.5 on 2023-11-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_management', '0013_rename_ademicyear_academicyear_and_more'),
        ('user_account', '0007_managementprofil_city_managementprofil_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0, max_length=2)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.academicyear')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.career')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.subject')),
            ],
        ),
    ]
