# Generated by Django 4.1.5 on 2024-01-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
        ('module_assessments', '0001_initial'),
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.academicyear'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.career'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.semester'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.academicyear'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.career'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.semester'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.subject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_assessments.typeofevaluation'),
        ),
    ]
