# Generated by Django 4.1.5 on 2024-01-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_assessments', '0001_initial'),
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.academicyear'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.career'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.semester'),
        ),
    ]
