# Generated by Django 4.1.5 on 2023-11-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_managementprofil_city_managementprofil_sex'),
        ('school_management', '0013_rename_ademicyear_academicyear_and_more'),
        ('module_assessments', '0002_assessment_type_evaluation_alter_assessment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='bulletins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.academicyear')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.career')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_management.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.student')),
            ],
        ),
    ]
