# Generated by Django 4.1.5 on 2024-01-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_content', '0003_alter_folder_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
